# Generated by Django 5.2.6 on 2025-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_ignace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreignace',
            name='code_kristianina',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
