# Generated by Django 5.2.6 on 2025-09-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembreTrinite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_kristianina', models.CharField(max_length=20, unique=True)),
                ('code_fianakaviana', models.CharField(max_length=50)),
                ('code_fianakaviana_niaviana', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('date_naissance', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('voina_vahatra_tafika', models.CharField(blank=True, choices=[('voina', 'Voina'), ('vahatra', 'Vahatra'), ('tafika', 'Tafika')], max_length=10)),
                ('mariage_ok', models.BooleanField(default=False)),
                ('mariage_date', models.DateField(blank=True, null=True)),
                ('batemy_ok', models.BooleanField(default=False)),
                ('batemy_date', models.DateField(blank=True, null=True)),
                ('confesy_ok', models.BooleanField(default=False)),
                ('komnio_ok', models.BooleanField(default=False)),
                ('kofirmasion_ok', models.BooleanField(default=False)),
                ('filaharana_ok', models.BooleanField(default=False)),
                ('andraikitra', models.JSONField(blank=True, default=list)),
                ('faritra', models.CharField(blank=True, max_length=100)),
                ('apv', models.CharField(blank=True, max_length=100)),
                ('fm_vm', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code_kristianina'],
            },
        ),
    ]
